DROP TABLE IF EXISTS igift_wishlists;

CREATE TABLE igift_wishlists (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    cost INTEGER,
    checked BOOLEAN,
    profile_id INTEGER
        REFERENCES igift_profiles(id) ON DELETE CASCADE NOT NULL
);

INSERT INTO igift_wishlists (name, cost, checked, profile_id)
    VALUES
        ('soundbar', 100, true, 1),
        ('chocolate', 10, true, 1),
        ('air fryer', 50, true, 2),
        ('cookbook', 20, true, 2),
        ('socks', 10, false, 2),
        ('mochi', 50, true, 3),
        ('oven mitts', 20, true, 3),
        ('fishing rod', 100, true, 4),
        ('puppy', 75, true, 5),
        ('wool socks', 20, true, 6),
        ('nylabone chewtoy', 20, true, 7),
        ('chemistry set', 50, true, 8),
        ('beer', 25, true, 8),
        ('bicycle', 200, true, 9),
        ('chocolate turtles', 20, true, 9);

--ALTER SEQUENCE igift_user_id_sequence RESTART WITH igift_wishlists.length + 1;