DROP TABLE IF EXISTS igift_wishlists;

CREATE TABLE igift_wishlists (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    cost INTEGER,
    checked BOOLEAN,
    profile_id INTEGER
        REFERENCES igift_profiles(id) ON DELETE CASCADE NOT NULL
);